'''
Created on 2014. 4. 7.

Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

@author: Alice
'''

if __name__ == '__main__':
    from Triangle import Triangle
    
    t = Triangle()
    find = False
    n = 1
    divisor_counter = 0
    divisor_list = []
    nth = 0
    target = 500
    
    while not find:
        nth = t.get_nth(n)
        for i in xrange(1, nth + 1):
            if nth % i == 0:
                divisor_counter += 1
#                 divisor_list.append(i)
        if len(divisor_list) > target:
            find = True
        else:
            n += 1
            divisor_counter = 0
#             divisor_list = []
        
    print nth, divisor_counter            